### ISSUE TITLE
Compilation on Windows 10 64 bit

### ISSUE THREAD

**Issue by maurosgroi** [cp2k/libint-cp2k#2] opened 2020-12-19 09:17 UTC
Dear Developers,
I'm trying to compile the library with fortran bindings using the cygwin64 toolchain.
Making make install, I got the following error:

(cd fortran && make) || exit 1
make[1]: Entering directory '/home/sgroi/apps/source/libint-v2.6.0-cp2k-lmax-4/fortran'
g++ -E -DHAVE_CONFIG_H -D__COMPILING_LIBINT2=1 -D__COMPILING_LIBINT2=1 -I../include -I..//include -I/usr/include -O3  ../include/libint2.h > ../include/libint2.h.i
python c_to_f.py ../include/libint2.h.i libint2_types_f.h Libint_t
grep '^#' ../include/libint2_types.h | grep -v '#include' > fortran_incldefs.h
FC libint_f.o
../include/libint2/util/generated/libint2_params.h:29:0:

   29 | #    if __has_include(<libint2_params.h>)
      |
Error: missing '(' before "__has_include" operand
../include/libint2/util/generated/libint2_params.h:29:0: Error: operator "__has_include" requires a header-name
make[1]: *** [../MakeSuffixRules:12: libint_f.o] Error 1
make[1]: Leaving directory '/home/sgroi/apps/source/libint-v2.6.0-cp2k-lmax-4/fortran'
make: *** [Makefile:38: fortran] Error 1

I configured with: ./configure --with-gnu-ld --with-cxx-optflags=-O3 --with-cxx=g++ --enable-fortran=yes --with-fc=gfortran

Thanks a lot for the help.
Best regards,
Mauro Sgroi.

**Comment by dev-zero** [comment] 2021-01-23 13:26
sorry for the late reply, this is actually not an issue with Windows or libint, but rather a regression in gcc-10, see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95889
Duplicate of #3

**Closed by dev-zero** 2021-01-23 13:26 UTC
